name: CI
on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Lake
        run: ros install lake
      - name: Run tests
        run: |
          PATH="~/.roswell/bin:$PATH"
          lake test
      - name: Generate Documents
        run: |
          PATH="~/.roswell/bin:$PATH"
          lake gendoc
