name: CI
on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Run test codes
        run: |
          ros config set dynamic-space-size 4gb
          ros ./roswell/cl-waffe-test.ros
      - name: Generate documents
        run: |
          ros ./roswell/gendoc.ros
      - name: Upload generated documents
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: build
          # A file, directory or wildcard pattern that describes what to upload
          path: docs/build
          retention-days: 90
      - name: Push Documents
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b gh-pages
          git add ./docs
          git commit -m "Updated Documentations"
          git push origin gh-pages
